site_name: Gliders Documentation
site_url: https://haydenwu2048.github.io/gliders-mkdocs-test/
theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - content.action.edit
    - search.suggest
    - search.highlight
    - content.tabs
nav:
  - Home: index.md
  - How-to Guides:
      - How to generate an SSH key pair: how/ssh-key.md
      - How to clone a GitLab repository with SSH: how/gitlab-repo-ssh.md
  - Glider Data Pipeline: gdp/gdp.md
# Built-in search
plugins:
  - search

# Useful Markdown extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - tables
  - attr_list
  - def_list
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true # have to include this
